# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0003_auto_20180818_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolemember',
            unique_together=set([('user', 'role')]),
        ),
    ]
