# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20180818_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
