# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_auto_20180821_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ManyToManyField(through='languages.LanguageSkill', to='languages.Language')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='languageskill',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.SkillLevel'),
        ),
        migrations.AddField(
            model_name='languageskill',
            name='programmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Programmer'),
        ),
        migrations.AlterUniqueTogether(
            name='languageskill',
            unique_together=set([('programmer', 'language')]),
        ),
    ]
